export const locations = [
  { title: "Auckland", value: "Auckland" },
  { title: "Dunedin", value: "Dunedin" },
  { title: "Wellington", value: "Wellington" },
  { title: "Christchurch", value: "Christchurch" },
  { title: "Hamilton", value: "Hamilton" },
  { title: "Tauranga", value: "Tauranga" },
  { title: "Napier", value: "Napier" },
  { title: "Hastings", value: "Hastings" },
  { title: "Dunedin", value: "Dunedin" },
  { title: "Palmerston North", value: "Palmerston North" },
  { title: "Nelson", value: "Nelson" },
  { title: "Rotorua", value: "Rotorua" },
  { title: "New Plymouth", value: "New Plymouth" },
  { title: "Whangarei", value: "Whangarei" },
  { title: "Invercargill", value: "Invercargill" },
  { title: "Whanganui", value: "Whanganui" },
  { title: "Gisborne", value: "Gisborne" },
  { title: "Taupo", value: "Taupo" },
];
